### ISSUE TITLE
在哪修改生日和文案的信息？

### ISSUE THREAD

**Issue by erkangkang** [shuakami/wuhu-home-Caidan#1]
### 问题描述

在部署完成后进入的入口和最后生日快乐的地方，如何修改生日信息？感谢！

**Comment by shuakami** [comment]
您好。我正在撰写文档，其中包括了非常详细的源代码修改教程。您很着急吗？如果您不着急的话，我会在文档部署完毕并上线后通知您。这个过程可能要4-7天。
反之，如果您很急的话，我可以简要的告诉您位置。

**Comment by shuakami** [comment]
*而且在刚刚我强制推送了一个经过修剪后的项目工程，建议您重新clone一下

**Comment by shuakami** [comment]
您好，项目文档已基本部署完毕，您可以前往[https://docs.sdjz.wiki/docs/birthday/intro](https://docs.sdjz.wiki/docs/birthday/intro)查看关于本项目的文档内容。如果您有不理解的地方欢迎您回复。
如您无异议，此comment将会在七天后关闭

**Comment by erkangkang** [comment]
好的，感谢大佬!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月21日(周日) 晚上6:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shuakami/wuhu-home-Caidan] 在哪修改生日和文案的信息？ (Issue #1)




 
您好，项目文档已基本部署完毕，您可以前往https://docs.sdjz.wiki/docs/birthday/intro查看关于本项目的文档内容。如果您有不理解的地方欢迎您回复。
 如您无异议，此comment将会在七天后关闭

**Comment by shuakami** [comment]
不客气！祝您生活愉快！
